apiVersion: apps/v1
kind: Deployment
metadata:
  name: void-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: void
  template:
    metadata:
      labels:
        app: void
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: void-files-pvc
        - name: config
          persistentVolumeClaim:
            claimName: void-config-pvc
      containers:
        - name: void
          image: grimreapermortis/void:latest
          imagePullPolicy: Always
          # envFrom:
          #   - secretRef:
          #       name: void-secrete
          # env:
          #   - name: BOT_URL
          #     value: http://$(BOT_SERVICE_SERVICE_HOST):$(BOT_SERVICE_SERVICE_PORT)/bot
          volumeMounts:
            - name: storage
              mountPath: /var/www/void
              readOnly: false
            - name: config
              mountPath: /etc/nginx/htpasswd
              readOnly: true
          ports:
            - containerPort: 8003
