apiVersion: v1
kind: PersistentVolume
metadata:
  name: void-files-pv
  namespace: prod
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /services/void
    server: 10.0.2.2
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: void-files-pvc
    namespace: prod
  mountOptions:
    - rw
    - bg
    - hard
    - nfsvers=4.2
    - rsize=524288
    - wsize=524288
    - tcp
    - timeo=600
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: void-config-pv
  namespace: prod
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /configs/void
    server: 10.0.2.2
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: void-config-pvc
    namespace: prod
  mountOptions:
    - rw
    - bg
    - hard
    - nfsvers=4.2
    - rsize=524288
    - wsize=524288
    - tcp
    - timeo=600
