apiVersion: v1
kind: PersistentVolume
metadata:
  name: void-files-pv
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/pi/files
    server: 192.168.1.2
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: void-files-pvc
    namespace: demo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: void-config-pv
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/pi/config
    server: 192.168.1.2
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: void-config-pvc
    namespace: demo