apiVersion: v1
kind: PersistentVolume
metadata:
  name: void-files-pv
  namespace: demo
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /media/sdb1/nfs/void
    server: 192.168.10.1
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: void-files-pvc
    namespace: demo

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-config-pv
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /media/sdb1/nfs/config
    server: 192.168.10.1
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: demo-config-pvc
    namespace: demo
