apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: void-files-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: void-config-pvc
  namespace: prod
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
